#!/bin/bash

source helpers.sh

# the same configuration is used in production!
source configuration.sh


################
# Prerequisites#
################

_test_case "Checks if the configuration makes sense"

[ -d $CMAKE_SOURCE_DIR ] || _error_cmake "no ${c} $CMAKE_SOURCE_DIR directory ${r}\nCannot configure project"

for i in ${TOOLCHAIN_FILES[*]}; do
    [ -f $i ] || _error_cmake "no ${c} $i ${r   } toolchain file in ${CMAKE_SOURCE_DIR}"
done

##########
# Action #
##########

./configure


########
# Tests#
########

for i in ${TOOLCHAIN_FILES[*]}; do
    output_dirs+=" ${CMAKE_OUTPUT_DIR}-${i}"
done

for d in ${output_dirs[*]}; do
    [ -d $d ] || _error_cmake "no ${c} $d ${r} directory created"
done

_test_case "projects must build tests (not run) for each target: can be run on target"

for cfg in ${CONFIGURATIONS_SUPPORTING_TESTS[*]}; do
    LOGFILE=${CMAKE_OUTPUT_DIR}-$cfg/build-test.log
    cmake --build ${CMAKE_OUTPUT_DIR}-$cfg --target $PROJECT_NAME-test > ${LOGFILE} 2>&1
    _error_cmake "building tests failed for $cfg"
    _info_cmake "$cfg ok"
done

_test_case "projects must run tests on supported (on host) targets: can be run on this host"

for cfg in ${CONFIGURATIONS_SUPPORTING_TESTS_ON_HOST[*]}; do
    LOGFILE=${CMAKE_OUTPUT_DIR}-${cfg}/run-test.log
    cmake --build ${CMAKE_OUTPUT_DIR}-${cfg} --target run-test > ${LOGFILE} 2>&1
    _error_cmake "running tests failed for $cfg"
    _info_cmake "$cfg ok"
done

_test_case "projects must build"

for d in ${output_dirs[*]}; do
    LOGFILE=$d/build.log
    cmake --build $d --target ${PROJECT_NAME} > ${LOGFILE} 2>&1
    _error_cmake "build failed for $d"
    _info_cmake "$d ok"
done

_test_case "projects must run on supported (on host) targets"

for cfg in ${CONFIGURATIONS_SUPPORTING_RUNNING[*]}; do
    LOGFILE=${CMAKE_OUTPUT_DIR}-${cfg}/run.log
    cmake --build ${CMAKE_OUTPUT_DIR}-${cfg} --target run > ${LOGFILE} 2>&1
    _error_cmake "running failed for $cfg"
    _info_cmake "$cfg ok"
done
