#!/bin/bash

. helpers.sh
. configuration.sh

[ -d $CMAKE_SOURCE_DIR ] || _error_cmake "no ${c} $CMAKE_SOURCE_DIR directory ${r}\nCannot configure project" 

./configure


for i in ${TOOLCHAIN_FILES[*]}; do
    [ -f $i ] || _error_cmake "no ${c} $i ${r} toolchain file in ${CMAKE_SOURCE_DIR}"
done

for i in ${TOOLCHAIN_FILES[*]}; do
    output_dirs+=" ${CMAKE_OUTPUT_DIR}-${i}"
done

_info_cmake "---------------------------"
_info_cmake "will test ${output_dirs[*]}"

for d in ${output_dirs[*]}; do
    _info_cmake "testing: dir exists ${d}"
    [ -d $d ] || _error_cmake "no ${c} $d ${r} directory created"
done


_info_cmake "---------------------------"
_info_cmake "will test if projects build"

for d in ${output_dirs[*]}; do
    cmake --build $d --target all > build.log
    _error_cmake "build failed for $d"
done

_info_cmake "---------------------------"
_info_cmake "will test if projects have tests"

for d in ${output_dirs[*]}; do
    cmake --build $d --target run-tests > tests.log
    _error_cmake "running tests failed for $d"
done

_info_cmake "---------"
_info_cmake "Result ok"